### ISSUE TITLE
Will this library be updated to use jakarta.jms instead of javax?

### ISSUE THREAD

**Issue by jdelacruz9** [messaginghub/pooled-jms#23]
Just wondering if this library will be updated to use jakarta.jms instead of javax.jms. If that's the case, is there a timeline?

Thanks

**Comment by tabish121** [comment]
It will probably move at some point, but no schedule for that is set as of yet

**Comment by ibmmqmet** [comment]
For reference - the Spring Boot 3.x milestone releases have apparently removed the option to use this for now because of the jakarta requirement. See https://github.com/spring-projects/spring-boot/issues/28701 And although they have stated a target for 4Q22 as their official release date, it would take time to reinstate.

**Comment by tabish121** [comment]
See PR #26 for upcoming Jakarta JMS 3.0 switchover which should be merged once Qpid JMS 2.0 is released featuring same.

**Comment by tabish121** [comment]
Pooled-JMS 3.0.0 has been released which now utilizes Jakarta JMS 3 APIs

**Comment by gemmellr** [comment]
I noted the new release on the original Spring Boot 3.0.0-M1 removal issue, it has now been unwound on main to reinstate pooling support for 3.0.0-M3: https://github.com/spring-projects/spring-boot/issues/30865.
